# Generated by Django 2.1.7 on 2019-03-16 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Animal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('species', models.CharField(max_length=100)),
                ('population', models.PositiveIntegerField()),
                ('region', models.CharField(max_length=100)),
                ('diet_classification', models.CharField(choices=[('herbivore', 'Herbivore'), ('omnivore', 'Omnivore'), ('carnivore', 'Carnivore')], max_length=100)),
            ],
        ),
    ]
