stations_with_line_numbers = {
  'Bathurst':             'Line 2',
  'Bay':                  'Line 2',
  'Bayview':              'Line 4',
  'Bessarion':            'Line 4',
  'Bloor–Yonge':          'Line 1',
  'Broadview':            'Line 2',
  'Castle Frank':         'Line 2',
  'Chester':              'Line 2',
  'Christie':             'Line 2',
  'College':              'Line 1',
  'Coxwell':              'Line 2',
  'Davisville':           'Line 1',
  'Don Mills':            'Line 4',
  'Donlands':             'Line 2',
  'Downsview Park':       'Line 1',
  'Dufferin':             'Line 2',
  'Dundas':               'Line 1',
  'Dundas West':          'Line 2',
  'Dupont':               'Line 1',
  'Eglinton':             'Line 1',
  'Eglinton West':        'Line 1',
  'Ellesmere':            'Line 3',
  'Finch':                'Line 1',
  'Finch West':           'Line 1',
  'Glencairn':            'Line 1',
  'Greenwood':            'Line 2',
  'High Park':            'Line 2',
  'Highway 407':          'Line 1',
  'Islington':            'Line 2',
  'Jane':                 'Line 2',
  'Keele':                'Line 2',
  'Kennedy':              'Line 2',
  'King':                 'Line 1',
  'Kipling':              'Line 2',
  'Lansdowne':            'Line 2',
  'Lawrence':             'Line 1',
  'Lawrence East':        'Line 3',
  'Lawrence West':        'Line 1',
  'Leslie':               'Line 4',
  'Main Street':          'Line 2',
  'McCowan':              'Line 3',
  'Midland':              'Line 3',
  'Museum':               'Line 1',
  'North York Centre':    'Line 1',
  'Old Mill':             'Line 2',
  'Osgoode':              'Line 1',
  'Ossington':            'Line 2',
  'Pape':                 'Line 2',
  'Pioneer Village':      'Line 1',
  'Queen':                'Line 1',
  'Queens Park':          'Line 1',
  'Rosedale':             'Line 1',
  'Royal York':           'Line 2',
  'Runnymede':            'Line 2',
  'Scarborough Centre':   'Line 3',
  'Sheppard West':        'Line 1',
  'Sheppard–Yonge':       'Line 1',
  'Sherbourne':           'Line 2',
  'Spadina':              'Line 1',
  'St. Andrew':           'Line 1',
  'St. Clair':            'Line 1',
  'St. Clair West':       'Line 1',
  'St. George':           'Line 1',
  'St. Patrick':          'Line 1',
  'Summerhill':           'Line 1',
  'Union':                'Line 1',
  'Vaughan Metro Centre': 'Line 1',
  'Victoria Park':        'Line 2',
  'Warden':               'Line 2',
  'Wellesley':            'Line 1',
  'Wilson':               'Line 1',
  'Woodbine':             'Line 2',
  'York Mills':           'Line 1',
  'York University':      'Line 1',
  'Yorkdale':             'Line 1'
}

stations_with_rich_information = {
  'Bathurst':             { 'Line': 2, 'accessible': True,  'bathoom': False },
  'Bay':                  { 'Line': 2, 'accessible': False, 'bathoom': False },
  'Bayview':              { 'Line': 4, 'accessible': True,  'bathoom': False },
  'Bessarion':            { 'Line': 4, 'accessible': True,  'bathoom': False },
  'Bloor':                { 'Line': 1, 'accessible': False, 'bathoom': True  },
  'Broadview':            { 'Line': 2, 'accessible': True,  'bathoom': False },
  'Castle Frank':         { 'Line': 2, 'accessible': False, 'bathoom': False },
  'Chester':              { 'Line': 2, 'accessible': False, 'bathoom': False },
  'Christie':             { 'Line': 2, 'accessible': False, 'bathoom': False },
  'College':              { 'Line': 1, 'accessible': False, 'bathoom': False },
  'Coxwell':              { 'Line': 2, 'accessible': True,  'bathoom': False },
  'Davisville':           { 'Line': 1, 'accessible': False, 'bathoom': False },
  'Don Mills':            { 'Line': 4, 'accessible': True,  'bathoom': True  },
  'Donlands':             { 'Line': 2, 'accessible': False, 'bathoom': False },
  'Downsview Park':       { 'Line': 1, 'accessible': True,  'bathoom': False },
  'Dufferin':             { 'Line': 2, 'accessible': True,  'bathoom': False },
  'Dundas West':          { 'Line': 2, 'accessible': True,  'bathoom': False },
  'Dundas':               { 'Line': 1, 'accessible': True,  'bathoom': False },
  'Dupont':               { 'Line': 1, 'accessible': False, 'bathoom': False },
  'Eglinton West':        { 'Line': 1, 'accessible': True,  'bathoom': False },
  'Eglinton':             { 'Line': 1, 'accessible': True,  'bathoom': True  },
  'Ellesmere':            { 'Line': 3, 'accessible': False, 'bathoom': False },
  'Finch West':           { 'Line': 1, 'accessible': True,  'bathoom': False },
  'Finch':                { 'Line': 1, 'accessible': True,  'bathoom': True  },
  'Glencairn':            { 'Line': 1, 'accessible': False, 'bathoom': False },
  'Greenwood':            { 'Line': 2, 'accessible': False, 'bathoom': False },
  'High Park':            { 'Line': 2, 'accessible': False, 'bathoom': False },
  'Highway 407':          { 'Line': 1, 'accessible': False, 'bathoom': False },
  'Islington':            { 'Line': 2, 'accessible': False, 'bathoom': False },
  'Jane':                 { 'Line': 2, 'accessible': True,  'bathoom': False },
  'Keele':                { 'Line': 2, 'accessible': False, 'bathoom': False },
  'Kennedy':              { 'Line': 2, 'accessible': True,  'bathoom': True  },
  'King':                 { 'Line': 1, 'accessible': False, 'bathoom': False },
  'Kipling':              { 'Line': 2, 'accessible': True,  'bathoom': True  },
  'Lansdowne':            { 'Line': 2, 'accessible': False, 'bathoom': False },
  'Lawrence East':        { 'Line': 3, 'accessible': False, 'bathoom': False },
  'Lawrence West':        { 'Line': 1, 'accessible': True,  'bathoom': False },
  'Lawrence':             { 'Line': 1, 'accessible': True,  'bathoom': False },
  'Leslie':               { 'Line': 4, 'accessible': True,  'bathoom': False },
  'Main Street':          { 'Line': 2, 'accessible': True,  'bathoom': False },
  'McCowan':              { 'Line': 3, 'accessible': False, 'bathoom': False },
  'Midland':              { 'Line': 3, 'accessible': False, 'bathoom': False },
  'Museum':               { 'Line': 1, 'accessible': False, 'bathoom': False },
  'North York Centre':    { 'Line': 1, 'accessible': True,  'bathoom': False },
  'Old Mill':             { 'Line': 2, 'accessible': False, 'bathoom': False },
  'Osgoode':              { 'Line': 1, 'accessible': True,  'bathoom': False },
  'Ossington':            { 'Line': 2, 'accessible': False, 'bathoom': False },
  'Pape':                 { 'Line': 2, 'accessible': True,  'bathoom': False },
  'Pioneer Village':      { 'Line': 1, 'accessible': True,  'bathoom': False },
  'Queen':                { 'Line': 1, 'accessible': True,  'bathoom': False },
  'Queens Park':          { 'Line': 1, 'accessible': True,  'bathoom': False },
  'Rosedale':             { 'Line': 1, 'accessible': False, 'bathoom': False },
  'Royal York':           { 'Line': 2, 'accessible': False, 'bathoom': False },
  'Runnymede':            { 'Line': 2, 'accessible': False, 'bathoom': False },
  'Scarborough Centre':   { 'Line': 3, 'accessible': True,  'bathoom': False },
  'Sheppard West':        { 'Line': 1, 'accessible': True,  'bathoom': True  },
  'Sheppard–Yonge':       { 'Line': 1, 'accessible': True,  'bathoom': True  },
  'Sherbourne':           { 'Line': 2, 'accessible': False, 'bathoom': False },
  'Spadina':              { 'Line': 1, 'accessible': True,  'bathoom': False },
  'St. Andrew':           { 'Line': 1, 'accessible': True,  'bathoom': False },
  'St. Clair West':       { 'Line': 1, 'accessible': True,  'bathoom': False },
  'St. Clair':            { 'Line': 1, 'accessible': True,  'bathoom': False },
  'St. George':           { 'Line': 1, 'accessible': True,  'bathoom': False },
  'St. Patrick':          { 'Line': 1, 'accessible': True,  'bathoom': False },
  'Summerhill':           { 'Line': 1, 'accessible': False, 'bathoom': False },
  'Union':                { 'Line': 1, 'accessible': True,  'bathoom': False },
  'Vaughan Metro Centre': { 'Line': 1, 'accessible': True,  'bathoom': True  },
  'Victoria Park':        { 'Line': 2, 'accessible': True,  'bathoom': False },
  'Warden':               { 'Line': 2, 'accessible': False, 'bathoom': False },
  'Wellesley':            { 'Line': 1, 'accessible': False, 'bathoom': False },
  'Wilson':               { 'Line': 1, 'accessible': False, 'bathoom': False },
  'Woodbine':             { 'Line': 2, 'accessible': True,  'bathoom': False },
  'Yonge':                { 'Line': 1, 'accessible': True,  'bathoom': True  },
  'York Mills':           { 'Line': 1, 'accessible': True,  'bathoom': False },
  'York University':      { 'Line': 1, 'accessible': False, 'bathoom': False },
  'Yorkdale':             { 'Line': 1, 'accessible': False, 'bathoom': False }
}


stations_with_accessible_and_adjacent_stations = [
  { 'name': 'Kipling',       'accessible': True,  'east': 'Islington',     'west': None            },
  { 'name': 'Islington',     'accessible': False, 'east': 'Royal York',    'west': 'Kipling'       },
  { 'name': 'Royal York',    'accessible': False, 'east': 'Old Mill',      'west': 'Islington'     },
  { 'name': 'Old Mill',      'accessible': False, 'east': 'Jane',          'west': 'Royal York'    },
  { 'name': 'Jane',          'accessible': True,  'east': 'Runnymede',     'west': 'Old Mill'      },
  { 'name': 'Runnymede',     'accessible': False, 'east': 'High Park',     'west': 'Jane'          },
  { 'name': 'High Park',     'accessible': False, 'east': 'Keele',         'west': 'Runnymede'     },
  { 'name': 'Keele',         'accessible': False, 'east': 'Dundas West',   'west': 'High Park'     },
  { 'name': 'Dundas West',   'accessible': True,  'east': 'Lansdowne',     'west': 'Keele'         },
  { 'name': 'Lansdowne',     'accessible': False, 'east': 'Dufferin',      'west': 'Dundas West'   },
  { 'name': 'Dufferin',      'accessible': True,  'east': 'Ossington',     'west': 'Lansdowne'     },
  { 'name': 'Ossington',     'accessible': True,  'east': 'Christie',      'west': 'Dufferin'      },
  { 'name': 'Christie',      'accessible': False, 'east': 'Bathurst',      'west': 'Ossington'     },
  { 'name': 'Bathurst',      'accessible': True,  'east': 'Spadina',       'west': 'Christie'      },
  { 'name': 'Spadina',       'accessible': True,  'east': 'St George',     'west': 'Bathurst'      },
  { 'name': 'St George',     'accessible': True,  'east': 'Bay',           'west': 'Spadina'       },
  { 'name': 'Bay',           'accessible': False, 'east': 'Yonge',         'west': 'St George'     },
  { 'name': 'Yonge',         'accessible': True,  'east': 'Sherbourne',    'west': 'Bay'           },
  { 'name': 'Sherbourne',    'accessible': False, 'east': 'Castle Frank',  'west': 'Yonge'         },
  { 'name': 'Castle Frank',  'accessible': False, 'east': 'Broadview',     'west': 'Sherbourne'    },
  { 'name': 'Broadview',     'accessible': True,  'east': 'Chester',       'west': 'Castle Frank'  },
  { 'name': 'Chester',       'accessible': False, 'east': 'Pape',          'west': 'Broadview'     },
  { 'name': 'Pape',          'accessible': True,  'east': 'Donlands',      'west': 'Chester'       },
  { 'name': 'Donlands',      'accessible': False, 'east': 'Greenwood',     'west': 'Pape'          },
  { 'name': 'Greenwood',     'accessible': False, 'east': 'Coxwell',       'west': 'Donlands'      },
  { 'name': 'Coxwell',       'accessible': True,  'east': 'Woodbine',      'west': 'Greenwood'     },
  { 'name': 'Woodbine',      'accessible': True,  'east': 'Main Street',   'west': 'Coxwell'       },
  { 'name': 'Main Street',   'accessible': True,  'east': 'Victoria Park', 'west': 'Woodbine'      },
  { 'name': 'Victoria Park', 'accessible': True,  'east': 'Warden',        'west': 'Main Street'   },
  { 'name': 'Warden',        'accessible': False, 'east': 'Kennedy',       'west': 'Victoria Park' },
  { 'name': 'Kennedy',       'accessible': True,  'east': None,            'west': 'Warden'        }
]

durations = [
  { 'station_1': 'Kipling',       'station_2': 'Islington',     'duration': '2:24' },
  { 'station_1': 'Islington',     'station_2': 'Royal York',    'duration': '2:00' },
  { 'station_1': 'Royal York',    'station_2': 'Old Mill',      'duration': '1:58' },
  { 'station_1': 'Old Mill',      'station_2': 'Jane',          'duration': '1:29' },
  { 'station_1': 'Jane',          'station_2': 'Runnymede',     'duration': '1:16' },
  { 'station_1': 'Runnymede',     'station_2': 'High Park',     'duration': '1:15' },
  { 'station_1': 'High Park',     'station_2': 'Keele',         'duration': '1:13' },
  { 'station_1': 'Keele',         'station_2': 'Dundas West',   'duration': '1:13' },
  { 'station_1': 'Dundas West',   'station_2': 'Lansdowne',     'duration': '1:22' },
  { 'station_1': 'Lansdowne',     'station_2': 'Dufferin',      'duration': '1:03' },
  { 'station_1': 'Dufferin',      'station_2': 'Ossington',     'duration': '1:21' },
  { 'station_1': 'Ossington',     'station_2': 'Christie',      'duration': '1:32' },
  { 'station_1': 'Christie',      'station_2': 'Bathurst',      'duration': '1:08' },
  { 'station_1': 'Bathurst',      'station_2': 'Spadina',       'duration': '1:08' },
  { 'station_1': 'Spadina',       'station_2': 'St George',     'duration': '1:05' },
  { 'station_1': 'St George',     'station_2': 'Bay',           'duration': '1:14' },
  { 'station_1': 'Bay',           'station_2': 'Yonge',         'duration': '1:12' },
  { 'station_1': 'Yonge',         'station_2': 'Sherbourne',    'duration': '1:34' },
  { 'station_1': 'Sherbourne',    'station_2': 'Castle Frank',  'duration': '1:09' },
  { 'station_1': 'Castle Frank',  'station_2': 'Broadview',     'duration': '2:26' },
  { 'station_1': 'Broadview',     'station_2': 'Chester',       'duration': '1:15' },
  { 'station_1': 'Chester',       'station_2': 'Pape',          'duration': '1:10' },
  { 'station_1': 'Pape',          'station_2': 'Donlands',      'duration': '1:06' },
  { 'station_1': 'Donlands',      'station_2': 'Greenwood',     'duration': '1:17' },
  { 'station_1': 'Greenwood',     'station_2': 'Coxwell',       'duration': '1:09' },
  { 'station_1': 'Coxwell',       'station_2': 'Woodbine',      'duration': '1:23' },
  { 'station_1': 'Woodbine',      'station_2': 'Main Street',   'duration': '1:35' },
  { 'station_1': 'Main Street',   'station_2': 'Victoria Park', 'duration': '1:45' },
  { 'station_1': 'Victoria Park', 'station_2': 'Warden',        'duration': '3:18' },
  { 'station_1': 'Warden',        'station_2': 'Kennedy',       'duration': '3:35' }
]
