# Generated by Django 2.1.7 on 2019-03-07 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=300)),
                ('blue_score', models.IntegerField()),
                ('orange_score', models.IntegerField()),
                ('overtime', models.BooleanField(default=False)),
                ('overtime_length', models.IntegerField(default=0)),
            ],
        ),
    ]
