# Generated by Django 2.1.7 on 2019-03-07 13:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('blue_score', models.IntegerField()),
                ('orange_score', models.IntegerField()),
                ('overtime', models.BooleanField(default=False)),
                ('overtime_length', models.IntegerField(default=0)),
                ('description', models.CharField(max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='Goal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('game_time', models.IntegerField(default=0)),
                ('scorer', models.CharField(max_length=100)),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='games.Game')),
            ],
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=100)),
                ('rank', models.CharField(choices=[('BR', 'Bronze'), ('SL', 'Silver'), ('GL', 'Gold'), ('PL', 'Platinum'), ('DI', 'Diamond'), ('CH', 'Champion'), ('GC', 'Grand Champion')], max_length=100)),
                ('games', models.ManyToManyField(to='games.Game')),
            ],
        ),
    ]
